config/routes.rb
Rails.application.routes.draw do
  get 'appointments/new'

  root 'static_pages#home'
  resources :users
  resources :services, only: [:create]
  resources :appointments
  get 'login' => "sessions#new"
  post 'login' => "sessions#create"
  delete 'logout' => "sessions#destroy"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :user
  belongs_to :service

 def check_doctor_schedule
 	doctor_schedules = Appointment.where(doctor_id: self.doctor_id).where(status: "confirmed").where("start_time BETWEEN ? AND ?", self.start_time.beginning_of_day, self.start_time.end_of_day)
  		if doctor_schedules
	  		doctor_schedules.each do |schedule|
			 	if (self.start_time >= schedule.start_time) && (self.start_time <= (schedule.start_time + (schedule.service.duration/60).hours))
			  		return true
				end 
	  		end
	  		return false
  		end
 end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :service

	#Paperclip setup
	has_attached_file :image,
		styles: {thumbnail: "100x100>", medium: "300x300>", large: "600x600>"},
		default_url: "/images/:style/missing.png"
	validates_attachment :image, content_type: {content_type: ["image/jpg", "image/png", "image/jpeg", "image/gif"]}

end

app/models/service.rb
class Service < ActiveRecord::Base
	#Associations
	belongs_to :user
	has_many :photos, dependent: :destroy
	has_many :appointments

	#Validations
	validates :title, presence: true, length: {maximum: 255}
	
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save :downcase_email

	#Associations
	has_many :services, dependent: :destroy
	has_many :appointments

	#Validations
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true, length: {maximum: 255}
	validates :email, presence: true, length: {maximum: 255},format: {with: VALID_EMAIL_REGEX },
				uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, presence: true, length: {minimum: 5}
	validates :user_type, presence: true

	private
	def downcase_email
		self.email = email.downcase
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include SessionsHelper
  include AppointmentsHelper

  def is_user_logged_in?
  	if current_user.nil?
  		flash[:warning] = "Please login first!"
  		redirect_to login_url
  	end
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	respond_to :js, :html

  def create
  	start_time = Time.new(params[:appointment]["start_time(1i)"].to_i,
  						  params[:appointment]["start_time(2i)"].to_i,
  						  params[:appointment]["start_time(3i)"].to_i,
  						  params[:appointment]["start_time(4i)"].to_i,
  						  params[:appointment]["start_time(5i)"].to_i)
  	@appointment = current_user.appointments.new(:start_time => start_time,
  											    :service_id => params[:appointment]["service_id"],
                            :doctor_id  => params[:appointment]["doctor_id"])
    if validate_appointment(appointment = @appointment)
      render js: "alert('Invalid Date or Time Seletion. Make sure your appointment time is greater than the current time.');"
    elsif @appointment.check_doctor_schedule
      render js: "alert('This time slot is already booked for the doctor.Try in some other time slot.');"
    else
  	if @appointment.save
  		respond_to do|format|
  			format.js
  		end
  	end
  end
  end

  def index
    @appointments = Appointment.where(status: "pending", doctor_id: current_user.id)
  end

  def update
    @appointment = Appointment.find_by_id(params[:id])
    @appointment.update_attributes(status: "confirmed")
  end

  def destroy
    @appointment = Appointment.find_by_id(params[:id])
    @appointment.destroy
  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	respond_to :js, :html

	def create
		@service = Service.new(service_params)

		respond_to do |format|
			if @service.save
			
				if !params[:image].blank?
					params[:image].each do |img|
						@service.photos.create(image: img)
					end
				end
				format.js {render 'create'}
			else
				format.js {render js: "Failed to create service" }
			end #if @service.save
		end #respond_to
	end #Create

	private

	def service_params
		params.require(:service).permit(:title,:duration,:price,:desc,:user_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			login user
			current_user
			redirect_to user
		else
			flash[:warning] = "Your email and password do not match!"
			render 'new'
		end
	end

	def destroy
		logout
		redirect_to root_url
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :is_user_logged_in?, only: [:show]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome to AppointU!"
  		login user=@user
  		current_user
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
    if current_user.user_type == "doctor"
      @services = current_user.services.order("created_at DESC")
    else
      @services = Service.order("title ASC")
    end
  	@user = current_user
  	@service = Service.new
  end

  private
  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation,:user_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

	def doctor_appointment_count
		Appointment.where(status: "pending", doctor_id: current_user.id).count
	end

	#Get Date and Time (IST) from start_time of Appointment
	def get_date(time)
		time.to_date
	end

	def get_ist(time)
		time.in_time_zone("Kolkata").strftime("%T %p")
	end

	#To validate an appointment while creating it
	def validate_appointment(appointment)
		DateTime.now > appointment.start_time
	end

end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
	end

	def current_user
		@curr_user ||= User.find_by_id(session[:user_id])
	end

	def logout
		@curr_user = nil
		session[:user_id] = nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_appointment.html.erb
<div id="pending_appointment_list" class="row">
	<div id="pending_appointment_<%= appointment.id %>" class="appointment-list col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
		<span>
			<%= "Service Name: #{appointment.service.title}" %><br />
			<%= "Patient Name: #{appointment.user.name}" %><br />
			<%= "Patient Email: #{appointment.user.email}" %><br />
			<%= "Date: #{get_date(appointment.start_time)}" %><br />
			<%= "Time: #{get_ist(appointment.start_time)}" %><br />
		</span>
			<%= link_to "Accept",appointment,method: :put,remote: true,class: "btn btn-success" %>
			<%= link_to "Reject",appointment,method: :delete, remote: :true,class: "btn btn-danger" %>
	</div>
</div>

app/views/appointments/_create_appointment_modal.html.erb
<div class="container-fluid">
  <!-- Modal -->
  <div class="modal fade" id="create_appointment_modal" role="dialog">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Appointment</h4>
        </div>
        <div class="modal-body">
          <%= form_for current_user.appointments.new, remote: true do |f| %>
            <%= f.hidden_field :service_id %>
            <%= f.hidden_field :doctor_id %>
            
            <div class="form-group">
              <%= f.label :start_time, "Select Date & Time:" %>
              <%= f.datetime_select :start_time, default: Date.today ,class: "form-control",placeholder: "Enter start time", class: "form-control" %>
            </div>
            <p id="error-message"></p>
            <div class="modal-footer">
              <%= f.submit "Appoint Me",class: "btn btn-default" %>
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/appointments/create.js.erb
alert('Your appointment has been created')
$('#create_appointment_modal').modal('hide')

app/views/appointments/destroy.js.erb
$("#appointment_badge").text("<%= doctor_appointment_count %>");
$("#pending_appointment_<%= @appointment.id %>").remove();

app/views/appointments/index.html.erb
<div class="container-fluid">
<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
		<h3 class="header-line">Appointments</h3>
	</div>
</div>
<%= render @appointments %>
</div>

app/views/appointments/new.js.erb
$("#create_appointment_modal").modal({
	show: true;
})

app/views/appointments/update.js.erb
$("#appointment_badge").text("<%= doctor_appointment_count %>");
$("#pending_appointment_<%= @appointment.id %>").remove();

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <%= link_to "AppointU", root_path ,class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
            <li><a href="<%= new_user_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
            <li><a href="<%= login_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% else %>

          <!-- If user is logged in -->
          <% if current_user.user_type == "doctor" %>
            <li><a href="<%= appointments_path %>">Appointments<span id="appointment_badge" class="badge"><%= doctor_appointment_count %></span></a></li>
            <li><%= link_to "Create Service","#", id: "create_service_link" %></li>
          <% end %> 
            <li><%= link_to current_user.email, current_user %></li>
            <li><a href="<%= logout_path %>" data-method="delete"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Appointu</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<%= render 'layouts/header' %>
</header>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>


<%= yield %>

</body>
</html>

app/views/services/_create_service_modal.html.erb
<div class="container-fluid">
  <!-- Modal -->
  <div class="modal fade" id="create_service_modal" role="dialog">
    <div class="modal-dialog modal-md">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Create Service</h4>
        </div>
        <div class="modal-body">
          <%= form_for @service, html: {multipart: true},remote: true do |f| %>

            <%= f.hidden_field :user_id, value: current_user.id %>
            <div class="form-group">
              <%= f.text_field :title,class: "form-control",placeholder: "Title" %>
            </div>

            <div class="form-group">
              <%= f.number_field :duration,class: "form-control",placeholder: "Duration in minutes (Example: 120)" %>
            </div>

            <div class="form-group">
              <%= f.number_field :price,class: "form-control",step: 'any',placeholder: "Price" %>
            </div>

            <div class="form-group">
              <%= f.text_area :desc,rows:5,cols:10,class: "form-control",placeholder: "Description" %>
            </div>

            <div class="form-group">
              <%= label_tag "Add Photos" %>
              <%= file_field_tag "image[]", type: :file, multiple: true %>
            </div>

            <div class="modal-footer">
              <%= f.submit "Create your service",class: "btn btn-default" %>
               <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          <% end %>
        </div>
                 
 
      </div>
    </div>
  </div>
</div>

app/views/services/create.js.erb
$("#create_service_modal").modal('hide');
<% if @service.photos.any? %>
	$("#service_list").append('<span class="col-lg-4 col-md-4 col-sm-4">'+
	'<div class="service-image"><img src="<%= @service.photos.first.image.url(:thumbnail)%>"></div><div class="service-title"><%= @service.title %></div></span>');
<% else %>
	$("#service_list").append('<span class="col-lg-4 col-md-4 col-sm-4">'+
	'<div class="service-image"><img src="/images/thumbnail/missing.png"></div><div class="service-title"><%= @service.title %></div></span>');
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class="alert alert-danger">
		Form contains <%= pluralize(object.errors.count,"error")%>
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/users/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 col-sm-8 col-sm-offset-2 col-xs-9 col-xs-offset-1">
			<div class="login-box">
				<h3>Sign up</h3>
			<%= form_for @user do |f| %>
				<div>
					<%= render "shared/error_messages", object: @user %>
				</div>
				<div class="form-group">
				<%= f.text_field :name,class: "form-control",placeholder: "Desired username" %>
				</div>

				<div class="form-group">
				<%= f.email_field :email,class: "form-control",placeholder: "Your email" %>
				</div>

				<div class="form-group">
				<%= f.password_field :password,class: "form-control",placeholder: "Password" %>
				</div>

				<div class="form-group">
				<%= f.password_field :password_confirmation,class: "form-control",placeholder: "Re-enter password" %>
				</div>

				<div class="form-group">
				<%= f.radio_button :user_type,"patient" %>Patient
				<%= f.radio_button :user_type, "doctor" %>Doctor
				</div>

				<div class="form-group">
				<%= f.submit "Create your account",class: "btn btn-default" %>
				</div>

			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= render 'services/create_service_modal' %>
<%= render 'appointments/create_appointment_modal' %>
<div class="container-fluid">
<div class="service-panel">
	<div id="service_list" class="row">
	<% @services.each_slice(3) do |services| %>
		
			<% services.each do |service| %>
				<span class="col-lg-4 col-md-4 col-sm-4 col-xs-4">

					<div class="service-image">
						<% if service.photos.present? && service.photos.first.image.present? %>
							<%= image_tag service.photos.first.image.url(:thumbnail) %>
						<% else %>
							<%= image_tag "/images/thumbnail/missing.png" %>
						<% end %>
					</div>

					<div class="service-title">
						<%= service.title %>
					</div>

					<% if current_user.user_type == "patient" %>
					<div>
						 <%= "By: Dr.#{service.user.name}" if service.user.present? %>
					</div>

					<div class="service-appoint">
						<% if service.user.present? %>
							<%= link_to "Appoint Me","#",id: "create_appointment_#{service.id}_#{service.user.id}", class: "btn btn-info new-appointment"%>
						<% else %>
							<%= link_to "Appoint Me","#",id: "create_appointment_#{service.id}", class: "btn btn-info new-appointment"%>
						<% end %>
					</div>
					<% end %>	

				</span>
			<% end %>
			<% end %>
		</div>

</div>
</div> 